# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_post',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
