# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='in_reply_to',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
